### PR TITLE
Support for Non-Browser Environments (Next.js Compatibility)

### PR DESCRIPTION
**Pull request by alea12**
Thank you for your great work! I had to use this patch to make this library working on Next.js build. Would appreciate it if you could merge this and create a new release 🙏

```
ReferenceError: window is not defined
```

### CODE REVIEW

**Comment by brianzinn** [comment]
I’ll merge and publish a new version. Thanks for the contribution. I’ll  reply here once a new version Is up  - appreciate if you can verify with Next.js. Cheers

**Comment by brianzinn** [comment]
hi @alea12 can you try `0.0.5` out when you get a chance? thanks again.

**Comment by alea12** [comment]
thank you @brianzinn. I haven't tested it yet, but I will let you know.

**Comment by alea12** [comment]
@brianzinn I can confirm that it worked with Next.js v14.2! Thank you for your quick release :)

**Comment by brianzinn** [comment]
sounds great - thank-you for your contribution.

**Pull request merged**
